import { Metadata } from "next";

export async function generateMetadata(): Promise<Metadata> {
    const title = "Terms of Service - Activepieces";
    const description = "Activepieces offers hundreds of apps to choose from to automate your work with."
    return {
        title: title,
        description: description,
        icons: "/favicon.ico",
        openGraph: {
            title: title,
            description: description,
            siteName: "Activepieces",
            images: [
                {
                    url: "https://www.activepieces.com/meta1.png",
                    width: 1200,
                    height: 630,
                    alt: "Activepieces",
                },
            ],
            url: "https://www.activepieces.com",
        }
    };
}

export default async function Privacy() {
    return (
        <div className="container mx-auto p-4 text-white">
            <h1 className="text-3xl font-bold mb-4">Terms of Service</h1>
            <p className="mb-8">Last updated: November 30, 2023</p>
            <p className="text-base font-normal mb-6">
                This Subscription Agreement (“Agreement”) is between Activepieces Inc. with offices at 95 Third Street, 2nd floor, San Francisco, CA 94103 (or, if a different corporate entity is listed as “Activepieces” on an Order Form [as defined below], (“Activepieces”), and the individual or entity signing or electronically accepting this Agreement, or any Order Form that references this Agreement (“Customer”). This Agreement is entered into on the earlier of, (a) Customer clicking “Agree” or “Yes” to the terms of this Agreement to gain initial access to, or use of, the Software, (b) Activepieces and Customer agreeing to an Order Form referencing this Agreement, or (c) Customer is given access to the Software (“Effective Date”).
            </p>
            <p className="text-base font-normal mb-6">
                Individual Signing on Behalf of Company. IF THE INDIVIDUAL ACCEPTING THIS AGREEMENT IS ACCEPTING ON BEHALF OF AN ENTERPRISE OR OTHER LEGAL ENTITY, SUCH INDIVIDUAL REPRESENTS THAT THEY HAVE THE AUTHORITY TO BIND SUCH ENTERPRISE AND ITS AFFILIATES TO THESE TERMS AND CONDITIONS, IN WHICH CASE THE TERM “CUSTOMER” SHALL REFER TO SUCH ENTERPRISE AND ITS AFFILIATES.
            </p><p className="text-base font-normal mb-6">
                Individual Not Authorized to Sign on Behalf of Company. IF THE INDIVIDUAL ACCEPTING THIS AGREEMENT DOES NOT HAVE SUCH AUTHORITY, OR DOES NOT AGREE WITH THESE TERMS AND CONDITIONS, SUCH INDIVIDUAL MUST NOT ACCEPT THIS AGREEMENT AND MAY NOT USE THE SERVICES OR SOFTWARE.
            </p><p className="text-base font-normal mb-6">
                Individual Signing on Behalf of Individual But Using Company Email. IF THE INDIVIDUAL ACCEPTING THIS AGREEMENT IS ACCEPTING THIS AGREEMENT ON HIS OR HER OWN BEHALF BUT USING AN ENTERPRISE EMAIL ADDRESS TO DO SO, SUCH INDIVIDUAL ACKNOWLEDGES AND AGREES THAT USE OF SUCH ENTERPRISE EMAIL ADDRESS WILL ESTABLISH A ACTIVEPIECES ACCOUNT THAT WILL BE ASSOCIATED WITH THE APPLICABLE ENTERPRISE, AND CAN AND WILL BE TRANSFERRED ENTIRELY (BOTH CONTROL AND DATA/INFORMATION WITHIN THE ACCOUNT) TO SUCH ENTERPRISE UPON SUCH COMPANY’S REQUEST WITHOUT NOTICE OR LIABILITY TO THE INDIVIDUAL. AS SUCH, TO ENSURE NO LOSS OF PERSONAL CONTENT, ACTIVEPIECES STRONGLY RECOMMENDS ESTABLISHING AN ACTIVEPIECES ACCOUNT TIED TO A PERSONAL EMAIL ADDRESS.
            </p><p className="text-base font-normal mb-6">
                Activepieces reserves the right to change, modify or remove portions of this Agreement at any time. Activepieces will provide you with 30 days’ notice prior to making any material changes by posting a notice on Activepieces’ website, by sending you an email and/or by some other means. The most current version of the Agreement will be posted at https://www.activepieces.com/terms.
            </p><h2 className="text-2xl font-bold mb-4">1. DEFINITIONS</h2><p className="text-base font-normal mb-6">
                “Acceptance” of an Order Form shall occur at the earliest of the following: (a) execution of an Order Form, (b) reference to an Order Form Quote No. within a purchase order or similar document, or (c) the use of Software.
            </p><p className="text-base font-normal mb-6">
                “Add-On User(s)” are additional Users in excess of those that have been purchased under a Subscription via an executed Order Form or web-portal purchase.
            </p><p className="text-base font-normal mb-6">
                “Affiliate” means any entity(ies) controlling, controlled by, and/or under common control with a party hereto, where “control” means the legal power to direct or cause the direction of the general management of the entity or the ownership of more than 50% of the voting securities in such entity.
            </p><p className="text-base font-normal mb-6">
                “Appendix” are inclusions in this Agreement that state the terms by which Software is offered to Customer. The Appendices shall be considered part of the Agreement.
            </p><p className="text-base font-normal mb-6">
                “Authorized Partner” is a reseller or distributor that is enabled and authorized to sell Software.
            </p><p className="text-base font-normal mb-6">
                “Community Edition Software” means the publicly available, community-developed open source software and components which may be provided with the Software. Community Edition Software is provided as Free Software (as defined herein).
            </p><p className="text-base font-normal mb-6">
                “Contractors” are defined as third parties that Customer has engaged to manage, or otherwise use the Software, solely on behalf of Customer.
            </p><p className="text-base font-normal mb-6">
                “Controlled Subject Matter” is the Software or any software or anything related thereto or any direct product thereof, collectively.
            </p><p className="text-base font-normal mb-6">
                “Customer Content” is all software, information, content and data provided by or on behalf of Customer or made available or otherwise distributed through the use of the Software.
            </p><p className="text-base font-normal mb-6">
                “Customer Records” collectively means books, records, contracts and accounts relating to the payments due to Activepieces under this Agreement.
            </p><p className="text-base font-normal mb-6">
                “Customer Success Services” means adoption services which are provided as part of the Subscription, as set forth in Appendix 1. Customer Success Services include the collection of Operational Data (as further stated in Appendix 1). Customer Success Services are only available to Customers who are purchasing Software, and are not available for Free Software.
            </p><p className="text-base font-normal mb-6">
                “Customer Support” means technical support of the Software provided by Activepieces.
            </p><p className="text-base font-normal mb-6">
                “Designated National” is any person or entity on the U.S. Department of Treasury’s List of Specially Designated Nationals or the U.S. Department of Commerce’s Table of Denial Orders.
            </p><p className="text-base font-normal mb-6">
                “Effective Price” means the actual price paid by Customer (List Price minus any applicable discount(s)) as set forth on an Order Form or as purchased via the Website.
            </p><p className="text-base font-normal mb-6">
                “Embargoed Countries” refers collectively to countries to which the United States maintains an embargo. “Enterprise” means the organization, company, corporation and/or other type of entity which procures the Software to be used on its behalf pursuant to the terms of this Agreement.
            </p><p className="text-base font-normal mb-6">
                “Fees” are those fees set forth within the Order Form, or, fees due immediately when purchasing via the web-portal.
            </p><p className="text-base font-normal mb-6">
                “Free Software” means a feature-limited version of Software provided to a Customer, User, end user, partner, or any other third party at no (or a greatly reduced cost) including but not limited to, the lowest tier offering of Software as made available by Activepieces.
            </p><p className="text-base font-normal mb-6">
                “Individual” means a person who uses the Software on their own behalf, and not an Enterprise. An Individual must be over the age of thirteen (13) years old.
            </p><p className="text-base font-normal mb-6">
                “List Price” means the list price of the Activepieces Software excluding (if applicable) any discount(s) set forth in an Order Form or as purchased via the Website.
            </p><p className="text-base font-normal mb-6">
                “Order Form” is a transactional document agreed to between the parties which states the Software and/or Supplemental Services being purchased, term of use, price, and other applicable transaction details. For the avoidance of doubt, the parties acknowledge and agree the terms and conditions stated within this Agreement and an executed Order Form shall govern with respect to all matters contemplated herein.
            </p><p className="text-base font-normal mb-6">
                “Purchase Order” is a Customer’s processing document, or similar record, which is used by Customer to demonstrate internal approval and /or record of a purchase. Any terms stated within a Purchase Order shall be null and void and are expressly rejected by the parties.
            </p><p className="text-base font-normal mb-6">
                “Software” means software, and other branded offerings made available by Activepieces or its Affiliate(s), including but not limited to, Activepieces’ DevOps Lifecycle Application Platform and applicable Supplemental Services.
            </p><p className="text-base font-normal mb-6">
                “Subscription” refers to the applicable services, support and function(s) of the Software as provided. Subscriptions are provided in tiers / levels as described in Appendix 1 and are based on the number of Users.
            </p><p className="text-base font-normal mb-6">
                “Subscription Start Date” is, unless otherwise agreed to in writing, the start date, (i) stated on an Order Form, or, the date in which Customer is given access to the Software (whichever is later), or (ii) as indicated via a Website transaction, regardless if such purchase is direct with Activepieces or via an Authorized Partner.
            </p><p className="text-base font-normal mb-6">
                “Subscription Term” shall begin on the Subscription Start Date and continue for twelve (12) months, unless the term length is otherwise agreed to in an Order Form or web-portal purchase.
            </p><p className="text-base font-normal mb-6">
                “Supplemental Services” means additional capacity, functionality, storage and/or other elements that Customer may procure separately for additional Fees. Supplemental Services may be purchased by Order Form or web-portal. Supplemental Services will be: (i) provided as a separate line item in an Order Form or web-portal purchase, and (ii) co-termed to the underlying Subscription Term if not purchased on the Subscription Start Date.
            </p><p className="text-base font-normal mb-6">
                “User(s)” is defined as the unique and single Individual, employee, Contractor, or other third-party individual or machine authorized by Customer (in accordance with this Agreement) that requires the provision of a seat within the admin platform, who are able to access the Software purchased under a Subscription, regardless of whether the User actually accesses, or the frequency with which they access, the Software. A User must be over the age of thirteen (13) years old.
            </p><p className="text-base font-normal mb-6">
                “Website” means Activepieces’ website located at www.activepieces.com and all subdomains, and all content, services, documentation provided on the Website.
            </p><h2 className="text-2xl font-bold mb-4">2. SCOPE OF AGREEMENT</h2><p className="text-base font-normal mb-6">
                This Agreement establishes a framework that will enable Activepieces to provide Customer with the Software. Software is provided as part of a Subscription, as described in Appendix 1. Software provided as a hosted solution, or Software-as-a-Service (“SaaS Software”), shall be subject to the attached Appendix 2 entitled “Software as a Service (SaaS) Offering”.
            </p><h2 className="text-2xl font-bold mb-4">3. ORDERING PROCESS</h2><p className="text-base font-normal mb-6">
                3.1 This Agreement applies to Software that Customer licenses directly from Activepieces, an Activepieces Affiliate, or from an Authorized Partner. For the avoidance of doubt, in the event Customer purchases from an Authorized Partner, Activepieces shall have no obligations to Customer with respect to any terms and conditions outside of this Agreement unless otherwise agreed to in writing between Customer and Activepieces.
            </p><p className="text-base font-normal mb-6">
                3.2 Unless otherwise agreed to between Customer and Activepieces in writing, the terms of this Agreement shall govern any and all use of the Software. Purchases of Software may take place by either:
            </p><p className="text-base font-normal mb-6">
                (i) purchasing via the Activepieces Website;
            </p><p className="text-base font-normal mb-6">
                (ii) executing an Order Form with Activepieces or an Affiliate of Activepieces; or
            </p><p className="text-base font-normal mb-6">
                (iii) purchase from an Authorized Partner.
            </p><p className="text-base font-normal mb-6">
                3.3 Activepieces and Customer acknowledge and agree that Free Software may be: (i) modified and/or updated, without notice, and (ii) limited in functionality, features, maintenance, support and contain other limitations not present in Software purchased. NOTWITHSTANDING THE “WARRANTY” AND “INDEMNIFICATION” SECTIONS BELOW, FREE SOFTWARE AND SOFTWARE OFFERED ON A TRIAL BASIS (AS STATED IN AN ORDER FORM OR WEB-PORTAL PURCHASE) ARE PROVIDED “AS-IS” WITHOUT ANY WARRANTY AND ACTIVEPIECES SHALL HAVE NO INDEMNIFICATION OBLIGATIONS NOR LIABILITY OF ANY TYPE WITH RESPECT TO SUCH FREE SOFTWARE UNLESS SUCH EXCLUSION OF LIABILITY IS NOT ENFORCEABLE UNDER APPLICABLE LAW, IN WHICH CASE ACTIVEPIECES’ LIABILITY WITH RESPECT TO SUCH FREE SOFTWARE SHALL NOT EXCEED $1,000.00USD.
            </p><h2 className="text-2xl font-bold mb-4">4. TERM AND TERMINATION</h2><p className="text-base font-normal mb-6">
                4.1 The Agreement commences on the Effective Date and continues until it is terminated in accordance with this Section 4.
            </p><p className="text-base font-normal mb-6">
                4.2 A Subscription Term shall begin as of the Subscription Start Date and remain in effect for the term length as indicated on the Order Form (the “Initial Term”) and automatically renew for successive twelve (12) month terms (each a “Renewal Term”) and for the same number of User licenses purchased in the most recent Subscription Term, plus any Add-On Users activated and/or used during such Subscription Term, unless either party gives notice of its intention not to renew thirty (30) days prior to the expiration of the current Subscription Term, or as otherwise agreed to between the parties. Customer shall have the right to opt-out of such renewal, from within the Software, commencing upon the Subscription Start Date until thirty (30) days prior to the expiration of the Subscription Term. Subscriptions must be used during the Subscription Term and any unused Subscriptions will expire.
            </p><p className="text-base font-normal mb-6">
                4.3 Either party may terminate this Agreement and any Order Form executed between the parties if:
            </p><p className="text-base font-normal mb-6">
                (a) the other party materially breaches this Agreement and does not cure the breach within thirty (30) days after written notice; or
            </p><p className="text-base font-normal mb-6">
                (b) the other party becomes the subject of a petition in bankruptcy or any other proceeding relating to insolvency, receivership, liquidation or assignment for the benefit of creditors.
            </p><p className="text-base font-normal mb-6">
                4.4 If Customer breaches the terms of Section 6, (Payment of Fees), Activepieces may (at its sole discretion) (a) suspend delivering Subscriptions until the breach is remedied or (b) avail itself of any other remedy under this Agreement, including terminating this Agreement under Section 4.3.
            </p><p className="text-base font-normal mb-6">
                4.5 Unless otherwise stated herein, termination of this Agreement shall not affect any Subscriptions currently being delivered and this Agreement shall remain in full force and effect until the expiration of the then-current Subscription Term. In the event this Agreement is terminated by Customer in accordance with Section 4.3, Activepieces will refund Customer any prepaid Fees for the prorated portion of unused Subscription Term. If this Agreement is terminated by Activepieces in accordance with this Section 4.3, Customer will pay (if applicable) any unpaid Fees covering the remainder of the Subscription Term of all Order Forms, to the extent permitted by applicable law. For the avoidance of doubt, in no event will termination relieve Customer of its obligation to pay any Fees payable to Activepieces for the period prior to the effective date of termination. The terms and conditions of this Agreement will apply to any Renewal Term(s) provided that, unless otherwise set forth in an Order Form, Website purchase or other written agreement between the Parties, Activepieces’ then-current List Price will apply with regard to any such Renewal Term(s). Activepieces reserves the right to increase fees for any Renewal Term(s) with respect to its products and services, including the Software and Supplemental Services.
            </p><h2 className="text-2xl font-bold mb-4">5. RESTRICTIONS AND RESPONSIBILITIES</h2><p className="text-base font-normal mb-6">
                5.1 Customer will not, and will not permit any third party to (not otherwise defined as a User):
            </p><p className="text-base font-normal mb-6">
                (i) use the Software for any purpose other than as specifically authorized in this Agreement;
            </p><p className="text-base font-normal mb-6">
                (ii) use the Software in such a manner that would enable any third party to access the Software; (iv) use the Software for time sharing or service bureau purposes (including without limitation, sublicensing, distributing, selling, reselling any Software);
            </p><p className="text-base font-normal mb-6">
                (iii) for any purpose other than its and its Affiliates’ own internal use;
            </p><p className="text-base font-normal mb-6">
                (iv) use the Software other than in compliance with all applicable laws and regulations;
            </p><p className="text-base font-normal mb-6">
                (v) use the Software in any manner that: (a) is harmful, fraudulent, deceptive, threatening, abusive, harassing, tortious, defamatory, vulgar, obscene, or libelous (including without limitation, accessing any computer, computer system, network, software, or data without authorization, breaching the security of another user or system, and/or attempting to circumvent any User authentication or security process); (b) impersonates any person or entity, including without limitation any employee or representative of Activepieces; (c) includes content, with respect to the use of SaaS Software, which is illegal or (d) introduces any virus, trojan horse, worm, time bomb, unsolicited bulk, commercial, or “spam” message, or other harmful computer code, file, or program (including without limitation, password guessing programs, decoders, password gatherers, keystroke loggers, cracking tools, packet sniffers, and/or encryption circumvention programs); and
            </p><p className="text-base font-normal mb-6">
                (vi) except to the extent permitted by applicable law, disassemble, reverse engineer, or decompile the Software or access it to: (a) build a competitive product or service, (b) build a product or service using similar ideas, features, functions or graphics of the Software, (c) copy any ideas, features, functions or graphics of the Software, or (d) determine whether the Software are within the scope of any patent.
            </p><p className="text-base font-normal mb-6">
                5.2 Nothing in this Agreement shall prohibit Customer from using the Software for benchmark testing or comparative analysis. Customer will comply with all applicable data privacy and security laws and shall have appropriate technological, administrative, and physical controls in place to ensure such compliance.
            </p><p className="text-base font-normal mb-6">
                5.3 In accordance with this Agreement, Activepieces has the right to verify electronically (or otherwise), and generate, or require Customer to generate and provide, reports related to Customer’s installation of, access to, and use of the Software to ensure compliance with the terms of this Agreement. Customer shall maintain Customer Records during the term of this Agreement and for two (2) years thereafter. Activepieces may, upon thirty (30) days’ prior written notice to Customer and during Customer’s normal business hours and subject to industry-standard confidentiality obligations, hire an independent third-party auditor to audit the Customer Records only to verify the amounts payable under this Agreement with respect to Customer usage of the Software. If an audit reveals underpayment, Customer shall promptly pay the deficiency to Activepieces plus late fees pursuant to Section 6. Activepieces shall bear the cost of an audit unless the audit reveals underpayment by more than 5% for the audited period, in which case Customer shall promptly pay Activepieces for the reasonable costs of the audit.
            </p><p className="text-base font-normal mb-6">
                5.4 Customer will be responsible for the following:
            </p><p className="text-base font-normal mb-6">
                (i) maintaining the security of Customer’s account, passwords (including, but not limited to, administrative and User passwords) and files, and for all uses of Customer account with or without Customer’s knowledge or consent; and
            </p><p className="text-base font-normal mb-6">
                (ii) any acts or omissions carried out by Contractors on Customer’s behalf. Customer shall ensure that Contractors are subject to terms no less stringent than those stated herein.
            </p><p className="text-base font-normal mb-6">
                5.5 Subject to this Agreement and the applicable Order Form, Activepieces will provide Customer Support to Customer for the Subscriptions, during the Subscription Term, at no additional cost. Details regarding Customer Support can be found in Appendix 1.
            </p><p className="text-base font-normal mb-6">
                5.6 Portions of the Software are governed by underlying open source licenses as described at https://github.com/activepieces/activepieces/blob/main/LICENSE. This Agreement and applicable Appendix(eces) establish the rights and obligations associated with Subscriptions and Software and are not intended to limit Customer’s right to software code under the terms of an open source license.
            </p><p className="text-base font-normal mb-6">
                5.7 Customer acknowledges and agrees that:
            </p><p className="text-base font-normal mb-6">
                (i) Account names are administered by Activepieces on a “first come, first serve” basis;
            </p><p className="text-base font-normal mb-6">
                (ii) Intentional name squatting, or purchasing, soliciting, or selling of an account name is prohibited; and
            </p><p className="text-base font-normal mb-6">
                (iii) Activepieces reserves the right to remove, rename, or close inactive accounts at its discretion.
            </p><h2 className="text-2xl font-bold mb-4">6. PAYMENT OF FEES</h2><p className="text-base font-normal mb-6">
                6.1 With respect to purchases direct from Activepieces, all web-portal purchase Fees shall be due and payable immediately.
            </p><p className="text-base font-normal mb-6">
                6.2 With respect to purchases direct from Activepieces, the Order Form shall: (i) reference this Agreement; (ii) state the Subscription Term(s) and Subscription(s) that are being purchased; and (iii) state the Fees due for the applicable Subscription(s).
            </p><p className="text-base font-normal mb-6">
                6.3 With respect to purchases direct from Activepieces, such Order Form is hereby incorporated into this Agreement by reference. The parties hereby agree to the terms and conditions stated within this Agreement and those found within an Order Form to the exclusion of all other terms. The parties agree that all terms stated within a Purchase Order, or other similar document, shall be null and void and are expressly rejected.
            </p><p className="text-base font-normal mb-6">
                6.4 With respect to purchases direct from Activepieces, Customer will pay Activepieces the applicable Fees, including those for Supplemental Services, without any right of set-off or deduction. All payments will be made in accordance with the payment details stated within the applicable Order Form. If not otherwise specified: (i) Activepieces (or applicable Activepieces Affiliate) will invoice Customer for the Fees upon the Acceptance of an Order Form; and (ii) all Fees will be due and payable within thirty (30) days of Customer’s receipt of an invoice. Except as expressly set forth in this Agreement, all Fees paid or due hereunder (including prepaid amounts) are non-refundable, and no credit will be due, including without limitation if this Agreement is terminated in accordance with Section 4 herein.
            </p><p className="text-base font-normal mb-6">
                6.5 During the Subscription Term, Customer may, subject to this Agreement, activate and use Add-On Users. For the avoidance of doubt, Customer shall not have the right to report less than the number of Users originally purchased under the Subscription, and all Add-On Users shall be co-termed to the underlying Subscription Term.
            </p><p className="text-base font-normal mb-6">
                6.6 With respect to purchases direct from Activepieces, at the end of each three (3) month period, commencing up on the Subscription Start Date, (referred to herein as “Quarter” or “Quarterly”) during the Subscription Term, Activepieces will: (i) per Section 5.3, generate a report of Add-On User(s) activated and/or used during the Quarter (“Quarterly Usage Report”), and (ii) invoice Customer on a prorated basis for the remaining portion of the Subscription Term, with respect to the Add-On User(s) activated and/or used during the Quarter as captured by the Quarterly Usage Report. For the avoidance of doubt, Add-On User(s) will not be invoiced for the Quarter in which they were activated and/or used. A Quarterly Usage Report will be generated during the first three (3) Quarters of a Subscription Term. Upon expiration of the Subscription Term, Customer’s renewal of the Software shall be for the same number of User licenses purchased for the most recent Subscription Term, plus any Add-On Users activated and/or used during such Subscription Term, unless otherwise agreed to between the parties. Add-On User(s) that have been identified within the Quarterly Usage Report, shall be considered due and payable in accordance with this Section 6. In the event a Quarterly Usage Report cannot be generated, Customer shall report and pay for such Overage Users (as defined below) in compliance with Section 6.7. Unless the parties agree to an Effective Price for Add-On Users which is less than the List Price, as set forth in an Order Form or Website purchase, Add-On Users activated and/or used during a Subscription Term will be invoiced at the List Price in the most recent Order Form or Website purchase.
            </p><p className="text-base font-normal mb-6">
                6.7 In the event a Customer procures Software from an Authorized Partner, or, Activepieces is unable to: (i) verify and generate a Quarterly Usage Report, and/or (ii) collect payment(s) with respect to Quarterly Add-Ons as provided in the Quarterly Usage Report, Customer shall be obligated to: (a) provide a report no later than twelve (12) months following the Subscription Effective Date (“Annual Report”) of all Users from said Subscription Term (“Overage Users”), and (b) be obligated to pay for such Overage Users, for the previous twelve (12) months, at the then current List Price for the Activepieces Software. Overage Users subject to the Annual Report shall not include any pro-ration, set-off and/or deduction to account for term of use, or otherwise. Overage Users that have been identified in an Annual Report shall be considered due and payable in accordance with Section 6. In the event Overage Users are outstanding upon the expiration of a Subscription Term, Customer shall be obligated to pay for such Overage Users in order to renew the Software.
            </p><p className="text-base font-normal mb-6">
                6.8 Any unpaid Fees are subject to a finance charge of one percent (1.0%) per month, or the maximum permitted by law, whichever is lower, plus all expenses of collection, including reasonable attorneys’ fees. Fees under this Agreement are exclusive of any and all taxes or duties, now or hereafter imposed by any governmental authority, including, but not limited to any national, state or provincial tax, sales tax, value-added tax, property and similar taxes, if any. Fees under this Agreement shall be paid without any withholding or deduction. In the case of any deduction or withholding requirements, Customer will pay any required withholding itself and will not reduce the amount to be paid to Activepieces on account thereof.
            </p><h2 className="text-2xl font-bold mb-4">7. CONFIDENTIALITY</h2><p className="text-base font-normal mb-6">
                7.1 Each party (the “Receiving Party”) understands that the other party (the “Disclosing Party”) has disclosed or may disclose information relating to the Disclosing Party’s technology or business (hereinafter referred to as “Confidential Information”). Such Confidential Information shall be either: (i) identified as confidential at the time of disclosure; or (ii) the nature of such information and/or the manner of disclosure are such that a reasonable person would understand it to be confidential. Without limiting the foregoing, and subject to applicable open source license(s), the Software is considered Activepieces Confidential Information.
            </p><p className="text-base font-normal mb-6">
                7.2 The Receiving Party agrees: (i) not to divulge to any third person any such Confidential Information; (ii) to give access to such Confidential Information solely to those employees with a need to have access thereto for purposes of this Agreement; and (iii) to take the same security precautions to protect against disclosure or unauthorized use of such Confidential Information that the party takes with its own confidential information, but in no event will a party apply less than reasonable precautions to protect such Confidential Information.
            </p><p className="text-base font-normal mb-6">
                7.3 The Disclosing Party agrees that Section 7.2 will not apply with respect to any information for which the Receiving Party can document: (i) is or becomes generally available to the public without any action by, or involvement of, the Receiving Party; or (ii) was in its possession or known by it prior to receipt from the Disclosing Party; or (iii) was rightfully disclosed to it without restriction by a third party, or (iv) was independently developed without use of any Confidential Information of the Disclosing Party.
            </p><p className="text-base font-normal mb-6">
                7.4 The parties’ obligations with respect to the protection of Confidential Information shall remain in force for a period three (3) years following the receipt of such Confidential Information and shall survive any termination or expiration of this Agreement.
            </p><p className="text-base font-normal mb-6">
                7.5 Nothing in this Agreement will prevent the Receiving Party from disclosing Confidential Information pursuant to any judicial or governmental order, provided that the Receiving Party gives the Disclosing Party, when legally possible, reasonable prior notice of such disclosure to allow the Disclosing Party, at Disclosing Party’s cost, a reasonable opportunity to request confidential treatment or a protective order pertaining thereto prior to Receiving Party making such disclosure.
            </p><p className="text-base font-normal mb-6">
                7.6 Each party acknowledges and agrees that the other may suffer irreparable damage in the event of a breach of the terms of this Section 7 and that such party will be entitled to seek injunctive relief (without the necessity of posting a bond) in the event of any such breach.
            </p><p className="text-base font-normal mb-6">
                7.7 Both parties will have the right to disclose Confidential Information in connection with: (i) a required filing to a governmental authority (provided such party will use reasonable efforts to obtain confidential treatment or a protective order), or (ii) disclosures made to potential investors or acquirers, provided that at all times the Confidential Information shall be protected in a manner no less stringent as set forth in this Section 7.
            </p><p className="text-base font-normal mb-6">
                7.8 Activepieces may collect data with respect to, and report on the aggregate response rate and other aggregate measures of, the Software performance and Customer’s usage of the Software. An overview of such data can be found at https://www.activepieces.com/docs/about/telemetry. Notwithstanding the foregoing, Activepieces will not identify Customer to any third party as the source of any such data without Customer’s prior written consent.
            </p><h2 className="text-2xl font-bold mb-4">8. INTELLECTUAL PROPERTY RIGHTS</h2><p className="text-base font-normal mb-6">
                8.1 Subject to the terms and conditions of this Agreement, Activepieces hereby grants to Customer and its Affiliates a limited, non-exclusive, non-transferable, non-sublicensable license for Customer’s and its Affiliates’ Users to use, reproduce, modify, prepare derivative works based upon, and display the code of Software at the tier level selected by Customer, or as set forth in an Order Form, solely for: (i) its internal use in connection with the development of Customer’s and/or its Affiliates’ own software; and (ii) the number of Users for which Customer has paid Activepieces. Notwithstanding anything to the contrary, Customer agrees that Activepieces and/or its licensors (as applicable) retain all right, title and interest in and to all Software incorporated in such modifications and/or patches, and all such Software may only be used, copied, modified, displayed, distributed, or otherwise exploited in full compliance with this Agreement, and with a valid Subscription for the correct number of Users.
            </p><p className="text-base font-normal mb-6">
                8.2 Except as expressly set forth herein, Activepieces (and its licensors, where applicable) will retain all intellectual property rights relating to the Software and any suggestions, ideas, enhancement requests, feedback, or other recommendations provided by Customer, its Affiliates, Users or any third party relating to the Software (herein referred to as “Feedback Materials”), which are hereby assigned to Activepieces. For the avoidance of doubt, Feedback Materials shall not include Customer Confidential Information or intellectual property owned by Customer. This Agreement does not constitute a sale of the Software and does not convey to Customer any rights of ownership in or related to the Software or any other intellectual property rights.
            </p><p className="text-base font-normal mb-6">
                8.3 Customer shall not remove, alter or obscure any of Activepieces’ (or its licensors’) copyright notices, proprietary legends, trademark or service mark attributions, patent markings or other indicia of Activepieces’ (or its licensors’) ownership or contribution from the Software.
            </p><p className="text-base font-normal mb-6">
                8.4 Subject to Section 8.5, Customer represents it shall be responsible for, and retain all right, title, and interest in and to, Customer Content, subject to a limited license to Activepieces necessary for Activepieces’ provision of the Software and its development and improvement.
            </p><p className="text-base font-normal mb-6">
                8.5 If Customer applies a license to publicly-available Customer Content within the Software, Customer (i) licenses that Customer Content under the terms of the applicable license; and (ii) represents that Customer has sufficient rights in that Customer Content to do so.
            </p><p className="text-base font-normal mb-6">
                8.6 Customer grants to Activepieces the right to use Customer’s company name and logo in marketing and promotional materials, including earnings releases and calls, subject to Customer’s brand and trademark guidelines as provided to Activepieces from time to time.
            </p><h2 className="text-2xl font-bold mb-4">9. WARRANTY</h2><p className="text-base font-normal mb-6">
                9.1 During the Subscription Term, Activepieces represents and warrants that: (i) it has the authority to enter into this Agreement, (ii) the Software shall be provided in a professional and workmanlike manner by qualified personnel; and (iii) it will use commercial industry standard methods designed to ensure the Software provided to Customer does not include any computer code or other instructions, devices or techniques, including without limitation those known as disabling devices, trojans, or time bombs, that are intentionally designed to disrupt, disable, harm, infect, defraud, damage, or otherwise impede in any manner, the operation of a network, computer program or computer system or any component thereof, including its security or User data.
            </p><p className="text-base font-normal mb-6">
                9.2 If at any time Activepieces fails to comply with the warranties in this Section 9, Customer may promptly notify Activepieces in writing of any such noncompliance. Activepieces will, within thirty (30) days of receipt of such written notification, either correct the noncompliance or provide Customer with a plan for correcting the noncompliance. If the noncompliance is not corrected or if a reasonably acceptable plan for correcting the non-compliance is not established during such period, Customer may terminate this Agreement and receive a prorated refund for the unused portion of the Subscription Term as its sole and exclusive remedy for such noncompliance.
            </p><p className="text-base font-normal mb-6">
                9.3 EXCEPT AS SPECIFICALLY SET FORTH IN THIS AGREEMENT, THE SOFTWARE, SUPPLEMENTAL SERVICES AND CONFIDENTIAL INFORMATION AND ANYTHING PROVIDED IN CONNECTION WITH THIS AGREEMENT ARE PROVIDED “AS-IS,” WITHOUT ANY WARRANTIES OF ANY KIND. ACTIVEPIECES AND ITS LICENSORS HEREBY DISCLAIM ALL WARRANTIES, EXPRESS OR IMPLIED, INCLUDING, WITHOUT LIMITATION, ALL IMPLIED WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, TITLE, AND NON-INFRINGEMENT.
            </p><h2 className="text-2xl font-bold mb-4">10. INDEMNIFICATION</h2><p className="text-base font-normal mb-6">
                10.1 Activepieces will defend Customer from any claim, demand, suit or proceeding made or brought against Customer by a third party alleging the Software (excluding Free Software as set forth in Section 3.3) provided by Activepieces infringes or misappropriates such third party’s patent, copyright, trademarks, or trade secrets (a “Customer Claim”). Activepieces will indemnify and hold Customer harmless from any damages, reasonable attorneys’ fees and costs finally awarded against Customer as a result of a Customer Claim, or for amounts paid by Customer under a settlement approved (in writing) by Activepieces, provided Customer: (i) promptly notifies Activepieces in writing of the Customer Claim; (ii) gives Activepieces all reasonable assistance at Activepieces’ expense; and (iii) gives Activepieces sole control over defense and settlement thereof except that Activepieces may not settle any Customer Claim unless it unconditionally releases Customer of all liability. The foregoing obligations do not apply if: (v) the Customer Claim arises from Software or any part thereof that is modified by Customer, or at Customer’s direction, after delivery by Activepieces; (w) the Customer Claim arises from the use or combination of the Software or any part thereof with other products, processes or materials not provided by Activepieces where the alleged infringement relates to such combination; (x) Customer continues allegedly infringing activity after being notified thereof or after being informed of modifications that would have avoided the alleged infringement; (y) the Customer Claim arises from software not created by Activepieces, or (z) the Customer Claim results from Customer’s breach of this Agreement and/or applicable Order Forms. Notwithstanding the foregoing, in the event of a Customer Claim, Activepieces, at its discretion, option and expense, reserves the rights to: (a) modify the Software to make it non-infringing provided there is no material loss of functionality; (b) settle such claim by procuring the right for Customer to continue using the Software; or (c) if in Activepieces’ reasonable opinion neither (a) or (b) are commercially feasible, terminate the license to the Software and refund a pro-rata portion of the amount paid by Customer for such Software for the unused portion of the Subscription Term.
            </p><p className="text-base font-normal mb-6">
                10.2 Customer will defend Activepieces and its Affiliates against any claim, demand, suit or proceeding made or brought against Activepieces by a third party alleging: (i) that any Customer Content or Customer’s use of Customer Content with the Software or any software (or combination of software) provided by Customer and used with the Software, infringes or misappropriates such third party’s intellectual property rights, or (ii) arising from Customer’s use of the Software in an unlawful manner or in violation of the Agreement, the applicable documentation, or Order Form (each a “Activepieces Claim”). Customer will indemnify Activepieces from any damages, reasonable attorneys’ fees and costs finally awarded against Activepieces as a result of, or for any amounts paid by Activepieces under a settlement approved (in writing) by Customer of a Activepieces Claim, provided Activepieces: (x) promptly gives Customer written notice of the Activepieces Claim, (y) gives Customer sole control of the defense and settlement of the Activepieces Claim (except that Customer may not settle any Activepieces Claim unless it unconditionally releases Activepieces of all liability), and (z) gives Customer all reasonable assistance, at Customer’s expense. The above defense and indemnification obligations do not apply if a Activepieces Claim arises from Activepieces’ breach of this Agreement and/or applicable Order Form. 10.3 This Section 10 (Indemnification) states the indemnifying party’s sole liability to, and the indemnified party’s exclusive remedy against the other party for any third-party claim described in this section.
            </p><h2 className="text-2xl font-bold mb-4">11. LIMITATION OF LIABILITY</h2><p className="text-base font-normal mb-6">
                11.1 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, IN NO EVENT WILL EITHER PARTY OR THEIR LICENSORS BE LIABLE FOR ANY INDIRECT, PUNITIVE, INCIDENTAL, SPECIAL, CONSEQUENTIAL DAMAGES, LOSS OF REVENUE, ANTICIPATED PROFITS, LOST BUSINESS OR LOST SALES, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE), STRICT LIABILITY, OR OTHERWISE, EVEN IF SUCH PARTY HAS BEEN ADVISED OF THE POSSIBILITY OF DAMAGES.
            </p><p className="text-base font-normal mb-6">
                11.2 TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, THE TOTAL LIABILITY OF EACH PARTY AND ITS AFFILIATES AND LICENSORS ARISING OUT OF OR RELATED TO THIS AGREEMENT, WHETHER BASED IN CONTRACT, TORT (INCLUDING NEGLIGENCE OR STRICT LIABILITY), OR OTHERWISE, WILL NOT EXCEED, IN THE AGGREGATE, THE TOTAL AMOUNT PAID BY CUSTOMER OR ITS AFFILIATES HEREUNDER IN THE ONE YEAR PERIOD PRECEDING THE FIRST INCIDENT OUT OF WHICH THE LIABILITY AROSE. THE FOREGOING LIMITATIONS WILL APPLY NOTWITHSTANDING ANY FAILURE OF ESSENTIAL PURPOSE OF ANY LIMITED REMEDY, BUT WILL NOT LIMIT CUSTOMER’S OR ITS AFFILIATES’ PAYMENT OBLIGATIONS UNDER THE “PAYMENT OF FEES” SECTION ABOVE.
            </p><h2 className="text-2xl font-bold mb-4">12. U.S. GOVERNMENT MATTERS</h2><p className="text-base font-normal mb-6">
                12.1 Notwithstanding anything else, Customer acknowledges that Controlled Subject Matter is subject to trade control laws and regulations, including the U.S. Export Administration Regulations (“EAR”) and various sanctions programs administered by the U.S. Office of Foreign Assets Control (“OFAC”). Customer shall not export, re-export, or transfer the Controlled Subject Matter except as authorized by these laws and regulations.
            </p><p className="text-base font-normal mb-6">
                12.2 Without limiting the foregoing, Customer shall not export, re-export, or transfer the Controlled Subject Matter to i) to any Embargoed Country or region, including Cuba, Iran, North Korea, Syria, or the Crimea, Donetsk, and Luhansk regions of Ukraine, ii) to any party identified on or subject to the limitations of OFAC’s Specially Designated Nationals List, the Bureau of Industry and Security’s Entity, Unverified, or Denied Persons Lists, or iii) for any end use or end user prohibited by 15 C.F.R. 744, including, without limitation, proliferation activities relating to nuclear, missile, or chemical and biological weapons.
            </p><p className="text-base font-normal mb-6">
                12.3 Use of the Software is representation and warranty that the Customer, Customer personnel, or Contractors are not located in, under the control of, or a national or resident of an Embargoed Country or a Designated National.
            </p><p className="text-base font-normal mb-6">
                12.4 As defined in FAR section 2.101, any software and documentation provided by Activepieces are “commercial items” and according to DFAR section 252.2277014(a)(1) and (5) are deemed to be “commercial computer software” and “commercial computer software documentation.” Consistent with DFAR section 227.7202 and FAR section 12.212, any use modification, reproduction, release, performance, display, or disclosure of such commercial software or commercial software documentation by the U.S. Government will be governed solely by the terms of this Agreement and will be prohibited except to the extent expressly permitted by the terms of this Agreement.
            </p><h2 className="text-2xl font-bold mb-4">13. FORCE MAJEURE</h2><p className="text-base font-normal mb-6">
                13.1 Activepieces and Customer will not be liable for any default or delay in the performance of their respective non-monetary obligations, to the extent that such default or delay is caused, directly or indirectly, by fire, flood, earthquake, explosions, elements of nature, acts of God, acts or regulations of government bodies, nuclear, chemical or biological contamination, court orders arising out of circumstances other than a breach of this Agreement by the Non-performing Party (as defined below), acts of war, terrorism, riots, civil disorders, rebellions or revolutions, strikes, lockouts or labor difficulties, epidemics or by any other event or circumstance that is beyond the reasonable control of Activepieces or Customer. The party that is unable to perform shall be referred to as the “Non-performing Party”. Such an event or circumstance giving rise to the default or delay is hereby referred to as a “Force Majeure Event”.
            </p><p className="text-base font-normal mb-6">
                13.2 The Non-performing Party will be excused from any further performance of the non-monetary obligations affected by such Force Majeure Event for as long as such Force Majeure Event continues and the Non-performing Party continues to use commercially reasonable efforts to resume performance. The Non-Performing Party may terminate this Agreement if the Force Majeure Event continues for a period of thirty (30) days.
            </p><p className="text-base font-normal mb-6">
                13.3 Except as expressly excused in this Section 13, each party will continue to perform its respective obligations under this Agreement during a Force Majeure Event.
            </p><h2 className="text-2xl font-bold mb-4">14. SECURITY / DATA PROTECTION</h2><p className="text-base font-normal mb-6">
                14.1 Without limiting Activepieces’ obligations as stated in Section 7 (Confidentiality), Activepieces shall be responsible for establishing and maintaining a commercially reasonable information security program that is designed to: (i) ensure the security and confidentiality of the Customer Content; (ii) protect against any anticipated threats or hazards to the security or integrity of the Customer Content; (iii) protect against unauthorized access to, or use of, the Customer Content; and (iv) ensure that all subcontractors of Activepieces, if any, comply with all of the foregoing. In no case shall the safeguards of Activepieces’ information security program be less stringent than the information security safeguards used by Activepieces to protect its own commercially sensitive data. Customer shall use commercially reasonable security and anti-virus measures when accessing and using the Software and to prevent unauthorized access to, or use of the Software, and notify Activepieces promptly of any such unauthorized access or use of which it becomes aware.
            </p><p className="text-base font-normal mb-6">
                14.2 The parties acknowledge and agree that: (i) the Software is not designed for the purpose(s) of storing, processing, compiling or transmitting Sensitive Data (as defined herein), and (ii) Customer shall not use the Software, or otherwise provide to Activepieces without prior written consent, Sensitive Data under this Agreement. “Sensitive Data” means: (a) special categories of data enumerated in European Union Regulation 2016/679, Article 9(1) or any successor legislation; (b) patient, medical, or other protected health information regulated by the Health Insurance Portability and Accountability Act (as amended and supplemented) (“HIPAA”); (c) credit, debit, or other payment card data or financial account information, including bank account numbers or other personally identifiable financial information; (d) social security numbers, driver’s license numbers, or other government identification numbers; (e) other information subject to regulation or protection under specific laws such as the Children’s Online Privacy Protection Act or Gramm-Leach-Bliley Act (“GLBA”) (or related rules or regulations); or (f) any data similar to the above protected under foreign or domestic laws. Customer further acknowledges that the Software and related features are not intended to meet any legal obligations for these uses, including HIPAA and GLBA requirements, and that Activepieces is not a Business Associate as defined under HIPAA. Therefore, notwithstanding anything else in this Agreement, Activepieces has no liability for Sensitive Data processed in connection with Customer’s use of the Software.
            </p><p className="text-base font-normal mb-6">
                14.3 To the extent Customer has Users of the SaaS Software located in the People’s Republic of China, Customer represents and warrants that it has complied with all requirements of a “personal information processor,” as that term is defined under the Personal Information and Protection Law of the People’s Republic of China (“PIPL”). This includes the requirement to provide adequate notice and obtain all necessary consents from relevant Users prior to the overseas transfer and processing of Personal Data by Activepieces, as well as onward transfers and processing by Activepieces’ third-party subprocessors. In addition, Customer warrants, where required, that it will not transfer Personal Data without a security assessment, as described in PIPL, from the Cyberspace Administration of China.
            </p><h2 className="text-2xl font-bold mb-4">15. MISCELLANEOUS</h2><p className="text-base font-normal mb-6">
                15.1 If any provision of this Agreement is found to be unenforceable or invalid, that provision will be limited or eliminated to the minimum extent necessary so that this Agreement will otherwise remain in full force and effect and enforceable.
            </p><p className="text-base font-normal mb-6">
                15.2 This Agreement is not assignable, transferable or sublicensable by either party without the other party’s prior written consent, not to be unreasonably withheld or delayed; provided that either party may transfer and/or assign this Agreement to a successor in the event of a sale of all, or substantially all, of its business or assets to which this Agreement relates.
            </p><p className="text-base font-normal mb-6">
                15.3 Except as otherwise provided in this Section 15.3, this Agreement is the complete and exclusive statement of the mutual understanding of the parties and supersedes and cancels all previous written and oral agreements, communications and other understandings relating to the subject matter of this Agreement. All waivers and modifications to this Agreement must be in a writing signed or otherwise agreed to by each party, except as otherwise provided herein.
            </p><p className="text-base font-normal mb-6">
                15.4 No agency, partnership, joint venture, or employment is created as a result of this Agreement and neither party has any authority of any kind to bind the other in any respect whatsoever.
            </p><p className="text-base font-normal mb-6">
                15.5 In any action or proceeding to enforce rights under this Agreement, the prevailing party will be entitled to recover costs and attorneys’ fees.
            </p><p className="text-base font-normal mb-6">
                15.6 All notices under this Agreement will be in writing and will be deemed to have been duly given when received, if personally delivered; when receipt is electronically confirmed, if transmitted by facsimile or e-mail; and upon receipt, if sent by certified or registered mail (return receipt requested), postage prepaid. Any notices to Activepieces shall also include a copy to legal@activepieces.com.
            </p><p className="text-base font-normal mb-6">
                15.7 In addition to any rights that accrued prior to termination, the provisions of Sections 3.3, and 5 through 15 shall survive any termination of this Agreement.
            </p><p className="text-base font-normal mb-6">
                15.8 This Agreement will be governed by the laws of the State of Delaware, U.S.A. without regard to its conflict of laws provisions. The federal and state courts sitting in Delaware, U.S.A. will have proper and exclusive jurisdiction and venue with respect to any disputes arising from or related to the subject matter of this Agreement. The United Nations Convention on Contracts for the International Sale of Goods is expressly disclaimed by the Parties with respect to this Agreement and the transactions contemplated hereby. Activepieces may provide translations of this Agreement or other terms or policies. Translations are provided for informational purposes only and if there is any inconsistency or conflict between a translation and the English version, the English version will control.
            </p><h2 className="text-2xl font-bold mb-4">APPENDIX 1: Activepieces Subscriptions</h2><p className="text-base font-normal mb-6">
                Fees for the Subscriptions are based upon the number of Users and the applicable level of support and/or functionality of the Software, as set forth in the table below. In the event Customer does not reasonably comply with written specifications or instructions from Activepieces’ service engineers, regarding any support issue or request (including without limitation, failure to make backups of Customer Content or versions of Software) (each, a “Support Issue”), Activepieces may cease its support obligations to Customer with respect to such Support Issue upon fifteen (15) days written notice and Customer’s inability to cure such noncompliance within the notice period.
            </p><h3 className="text-l font-bold mb-4">SUBSCRIPTIONS AND LEVELS OF SUPPORT</h3>
            <table className="border-collapse border border-gray-400">
            <tr className="bg-gray-900">
                <td className="border border-gray-400 p-2"><strong>Subscription*</strong></td>
                <td className="border border-gray-400 p-2"><strong>Level of Support (First Response Time)</strong></td>
            </tr>
            <tr>
                <td className="border border-gray-400 p-2">Free, Pro</td>
                <td className="border border-gray-400 p-2">Activepieces Community Forum</td>
            </tr>
            <tr>
                <td className="border border-gray-400 p-2">Business, Platform</td>
                <td className="border border-gray-400 p-2">Activepieces Standard Support 48 hour First Time Response SLA</td>
            </tr>
            <tr>
                <td className="border border-gray-400 p-2">Enterprise</td>
                <td className="border border-gray-400 p-2">Defined in Order Form</td>
            </tr>
        </table>

            <p className="text-base font-normal mb-6">
                *Note: Subscription names are subject to change, however, the applicable Subscription for that tier shall remain the same during a Subscription Term.
            </p><h3 className="text-l font-bold mb-4">CUSTOMER SUCCESS SERVICES</h3><p className="text-base font-normal mb-6">
                Customer Success Services include additional assistance with respect to Customer’s use of the Activepieces Software. Customer Success Services are provided at no charge. In order to receive Customer Success Service(s), Customer acknowledges and agrees that additional data and information (“Operational Data”) will be collected to allow the operation of the Customer Success Services.
            </p><h2 className="text-2xl font-bold mb-4">APPENDIX 2: Software as a Service (SaaS) Offering</h2><p className="text-base font-normal mb-6">
                With respect to Customer’s purchase and/or use of the SaaS Software, the following additional terms shall apply.
            </p><h3 className="text-l font-bold mb-4">AVAILABILITY</h3><p className="text-base font-normal mb-6">
                Availability to the SaaS Software will be measured, and reported on, by Activepieces using instrumentation and observation tools specifically designed to provide a representative measure of service availability. You can find the status of the SaaS Offering here: https://status.activepieces.com/.
            </p><h3 className="text-l font-bold mb-4">BACKUPS</h3><p className="text-base font-normal mb-6">
                Activepieces will maintain a commercially reasonable system of data backup process and technology to ensure that primary data sources remain recoverable in the event of various system failures.
            </p><h3 className="text-l font-bold mb-4">MONITORING AND INCIDENT RESPONSE</h3><p className="text-base font-normal mb-6">
                Activepieces will employ a system of instrumentation and observation tools to ensure that system behavior which may limit use of the SaaS Software is detected and announced. Activepieces will also employ industry reasonable practices to maintain appropriate engineering personnel availability for the purposes of incident response(s).
            </p><h3 className="text-l font-bold mb-4">UPDATES AND UPGRADES</h3><p className="text-base font-normal mb-6">
                Activepieces will update the SaaS Software as updates are available and when reasonably practical to implement said updates. Update timing and process will remain at Activepieces’ discretion.
            </p><h3 className="text-l font-bold mb-4">SCHEDULED SYSTEM MAINTENANCE</h3><p className="text-base font-normal mb-6">
                Activepieces will occasionally perform scheduled system maintenance which requires limits to the use of part or all of the SaaS Software features, or significantly reduces features and functions during the scheduled system maintenance period. Activepieces will provide ten (10) business days’ notice for all scheduled system maintenance activities. Activepieces will take a proactive approach to minimizing the need for such maintenance and will limit scheduled system maintenance to less than four (4) hours per calendar month. Notwithstanding the foregoing, in the event of an emergency or urgent issue which may negatively impact Activepieces’ customers, Activepieces has the right to carry out unscheduled maintenance to remedy such instance(s). For the avoidance of doubt, such unscheduled maintenance shall: (i) be limited to only those issues which may negatively impact customers; and (ii) will be carried out in such a manner to provide for the least amount of disruption to customers.
            </p><h3 className="text-l font-bold mb-4">SUSPENSION OF SERVICE</h3><p className="text-base font-normal mb-6">
                Activepieces reserves the right to suspend service to the SaaS Software if: (i) Customer fails to comply with the Agreement and this Appendix, (ii) Customer exceeds set application limits, or (iii) requests or usage deemed malicious in nature is identified to be sourced from Customer accounts, personnel, or systems.
            </p><h2 className="text-2xl font-bold mb-4">Contact Us</h2><p className="text-base font-normal mb-6">
                In order to resolve a complaint regarding the Site, the Service or the Content or to receive further information
                regarding use of them, please contact us at:
            </p><address>
                Activepieces Inc. <br />
                256 Chapman Rd 105 #4 <br />
                Newark, DE 19702 <br />
                United States <br />
                <a href="mailto:support@activepieces.com">support@activepieces.com</a>
            </address>
        </div >
    );
}


